### ISSUE TITLE
Remove support for true/false in Generate annotation

### ISSUE THREAD

**Issue by linaori** [hostnet/accessor-generator-plugin-lib#1]
Currently according to the description:

```
@Enum({"public", "protected", "private", "none", true, false})
```

However, `true` and `false` are a deprecated functionality and should be avoided; see for example: https://github.com/hostnet/accessor-generator-plugin-lib/blob/master/src/Annotation/Generate.php#L54

**Comment by hboomsma** [comment]
will be supported until all references in our code are changed.

**Comment by linaori** [comment]
See #2, I don't see why this should be closed already
